### ISSUE TITLE
Add javascript demo in a new page section

### ISSUE THREAD

**Issue by etcadinfinitum** [UWB-ACM/website-example-2#2]
Would be nice to have a small javascript demo with interactive elements like buttons. This shouldn't be too complicated or difficult.

**Comment by etcadinfinitum** [comment]
Possible additions that would be good to demonstrate:
- button / alert combo 
- text box with text going to a `<p>` (good for demonstrating code injection/sanitization issues) 
- task list using react or another similar framework

**Comment by bpas247** [comment]
> task list using react or another similar framework

This should probably done in a separate repo, because it requires including js dependencies that would be more difficult to all manage via CDN. So you'd probably want to manage it with a package manager, like yarn or npm. You *might* be able to get away with just using CDN links as long as you don't use any js proposal-specific syntaxes that aren't support as a standard yet.

If we want to go with the separate repo route, we could just use a CodeSandbox repo
